### ISSUE TITLE
Error raised by utils.dump.dump_response() if the HTTPResponse's reason is None

### ISSUE THREAD

**Issue by chriscoomber** [sigmavirus24/requests-toolbelt#115]
Example:
responses produces a HTTPResponse object, but leaves the reason as None.
```python
import requests
import responses
from requests_toolbelt.utils import dump

@responses.activate
def main():
    responses.add(responses.GET, "http://example.com/", body='abc', status=200)
    rsp = requests.get("http://example.com/")
    data = dump.dump_response(rsp)
    print data

main()
```

Which causes error:
```
  File "/.../requests_toolbelt-0.5.0-py2.7.egg/requests_toolbelt/utils/dump.py", line 157, in dump_response
    _dump_response_data(response, prefixes, data)
  File "/.../requests_toolbelt-0.5.0-py2.7.egg/requests_toolbelt/utils/dump.py", line 99, in _dump_response_data
    _coerce_to_bytes(response.reason) + b'\r\n')
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

I think technically it's wrong to have reason=None, http://www.w3.org/Protocols/rfc2616/rfc2616-sec6.html says
```
Status-Line = HTTP-Version SP Status-Code SP Reason-Phrase CRLF
```
but the chosen text of the reason phrase is optional. Nevertheless it would be nice to handle it.

**Comment by sigmavirus24** [comment]
Hey @chriscoomber thanks for reporting this.

The `dump_response` is more for debugging purposes more than anything. If you're using it to fix responses, that's great! responses (when last I looked at it) was thoroughly incomplete and fragile. I don't see a reason to handle something that in *reality* doesn't happen though.

Cheers,
