### ISSUE TITLE
Guess Proxy Authentication

### ISSUE THREAD

**Issue by pcreech** [sigmavirus24/requests-toolbelt#125]
I am developing a 'GuessAuthProxyAuth' class for a project I'm working on that subclasses GuessAuth, and allows for guessing of both  HTTP authentication as well as Proxy Authentication.  Essentially, it does for Proxy authentication methods what GuessAuth does for HTTP authentication.

I would like to be able to contribute it here, since I feel others could potentially benefit from it.

**Comment by sigmavirus24** [comment]
Sounds good to me.
