### ISSUE TITLE
docs/contributing.rst file refer to non-existing CODE_OF_CONDUCT.rst

### ISSUE THREAD

**Issue by petterreinholdtsen** [sigmavirus24/requests-toolbelt#129]
This part of contributing.rst refer to a non-existing file:

 .. _code-of-conduct:
 .. include:: ../CODE_OF_CONDUCT.rst

I discovered this while building the Debian package, https://tracker.debian.org/pkg/python-requests-toolbelt .

**Comment by sigmavirus24** [comment]
The code of conduct is in the repository but probably not included in the source distribution. Sorry about that!
