### ISSUE TITLE
Requests 2.10.0

### ISSUE THREAD

**Issue by jaybaker** [sigmavirus24/requests-toolbelt#135]
Sorry, this is not an issue but a question.
Where/how can I get Requests 2.10.0 so that I can use requests-toolbelt?

**Comment by sigmavirus24** [comment]
If you're trying to use the toolbelt for Google App Engine, you have to wait for requests to create a 2.10.0 release first.

**Comment by jaybaker** [comment]
Thanks.

**Comment by seawolf42** [comment]
I've been using Requests 2.9.1 successfully with Google App Engine for some time now. It requires installing a couple other modules and patching all three. I've summarized the steps [here](http://stackoverflow.com/a/35109359/1886109). I don't know if this works with 2.10, though.

**Comment by sigmavirus24** [comment]
2.10.0 does not exist yet @seawolf42. When it does exist your steps will be unnecessary and I hope you'll edit them to prevent confusion.

**Comment by seawolf42** [comment]
That's great news, and when I can test and confirm this on GAE with 2.10.x I will be happy to do so. Where can I +1 so I'm notified of the 2.10.x release?

**Comment by sigmavirus24** [comment]
I'll make sure you find out here @seawolf42

**Comment by seawolf42** [comment]
I never heard back and this fell off my radar... does the official 2.10.0 release fix all the known App Engine issues? I'd love to update my SO answer if this is now a thing of the past.

**Comment by sigmavirus24** [comment]
It might. Honestly, I haven't tested it as I have no way of testing any of this. I suspect @Lukasa might know though.

**Comment by seawolf42** [comment]
I just ran some preliminary tests and it appears to be working fine on my staging server, so I think we're good. I'm getting an error on my local server (running dev_appserver.py), but I don't know if that's related.

---------- 
jeffrey k eliasen - technologist, philosopher, agent of change
blog <http://jeff.jke.net/> | linkedin <http://www.linkedin.com/pub/jeffrey-eliasen/3/a83/b76> | google+ <http://plus.google.com/+JeffreyEliasen> | facebook <http://facebook.com/jeffrey.eliasen> | twitter <http://twitter.com/jeffreyeliasen>

**Comment by Lukasa** [comment]
I believe it does, but am not sure. I know that urllib3 has at least one newer release than the one requests is using, which may contain extra fixes, but we're planning to ship a requests with that next week.

**Comment by seawolf42** [comment]
I ran it through everything we do and it's working, I've had it in production now for a couple days with no trouble. Looks like this is now officially working on App Engine.
