### ISSUE TITLE
MultipartEncoder: Requests hang during reading response - to_string changes position of the iterator

### ISSUE THREAD

**Issue by stardust85** [sigmavirus24/requests-toolbelt#143]
```
(testenv)[vagrant@oraclelinux7 ~]$ pip freeze|grep requests
requests==2.10.0
requests-toolbelt==0.6.0
````

Server: Sonatype Nexus (uses jetty)

Happens when trying to upload a file using endpoint 'service/local/artifact/maven/content'
Maybe only my local issue caused by the server or by incorrect usage. Just wanted to post it here for the case that somebody sees something similar. I will post more details tomorrow (hopefully) as well as prepare some easy way how to reproduce.

```
data = {
                    'g':local_artifact.group,
                    'a':local_artifact.artifact,
                    'v':local_artifact.version,
                    'r':repo_id,
                    'e': local_artifact.extension,
                    'p': local_artifact.extension,
                    'hasPom': 'false'
                }

data_list = data.items()
data_list.append( ('file', (filename, f, 'text/plain') ))
m = MultipartEncoder(fields=data_list)
headers = {'Content-Type': m.content_type}
```

actually the broken code is in my feature branch of repositorytools (https://github.com/stardust85/repositorytools/tree/streaming_upload)

**Comment by stardust85** [comment]
My fault. The problem was that I read the content while logging.

The method to_string() should move the iterator back to the beginning, not changing the internal state of the object!

**Comment by sigmavirus24** [comment]
> The method to_string() should move the iterator back to the beginning, not changing the internal state of the object!

Why? We document scenarios as *either* using the iterator *or* using `to_string()`. Further, given what we accept we cannot always move the iterator back to the beginning. If you want to add more documentation around this, that would be great, but I'm afraid we can't do much else in this case. Sorry

**Comment by stardust85** [comment]
I didn't find it in the docs. At least not in the docs of to_string(). And you're right that it may be tricky to move the pointer back.

**Comment by stardust85** [comment]
I created a pull request with improved docs...
