### ISSUE TITLE
Missing contributors in AUTHORS.rst

### ISSUE THREAD

**Issue by sigmavirus24** [sigmavirus24/requests-toolbelt#147]
I believe we're missing three contributors from our [AUTHORS.rst](https://github.com/sigmavirus24/requests-toolbelt/blob/dae57b597f231b4d18147cb53def5f5c411e3cb1/AUTHORS.rst) file

- [x] @snarfed 
- [x] @mikelambert 
- [x] @jonparrott

You're each welcome to send a PR to update the file or just let me know how you'd like to be credited and I'll update it for you.

:tada:

**Comment by snarfed** [comment]
aww thank you! `Ryan Barrett (https://snarfed.org/)` works for me.

**Comment by jonparrott** [comment]
I haven't actually written any code here so you can leave me off for now. :)

**Comment by mikelambert** [comment]
Thanks, `Mike Lambert (@mikelambert)` works for me. If I ever set up a proper website, I'll send a PR. :)

**Comment by sigmavirus24** [comment]
Thank y'all for your contributions. :-)
