### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'UUID' objects

### ISSUE THREAD

**Issue by rtaft** [sigmavirus24/requests-toolbelt#150]
I'm getting this error trying to use requests-toolbelt.

```
Traceback (most recent call last):
  File "myfile.py", line 210, in my_function
    data = dump.dump_all(response)
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/utils/dump.py", line 193, in dump_all
    dump_response(response, request_prefix, response_prefix, data)
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/utils/dump.py", line 154, in dump_response
    proxy_info=proxy_info)
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/utils/dump.py", line 73, in _dump_request_data
    bytearr.extend(prefix + _format_header(name, value))
  File "/usr/local/lib/python2.7/dist-packages/requests_toolbelt/utils/dump.py", line 39, in _format_header
    return (_coerce_to_bytes(name) + b': ' + _coerce_to_bytes(value) +
TypeError: cannot concatenate 'str' and 'UUID' objects
```

The specific call being used is for https://msdn.microsoft.com/en-us/library/partnercenter/mt644396.aspx.  I was trying to use this to get hex output of the response.  Specifically, if you look at the response at the bottom of that link, where it says 'Content-Length: 10' but the length should say 4, I was using requests-toolbelt to try to get a full response hexdump.  I'm not sure if that is related to the error as they have `0xFEFF` before the 'true'.

**Comment by sigmavirus24** [comment]
So, I would need more code before I can help you, but this looks like you have a `UUID` object in your header values (somewhere) and that's not at all what we expect. It seems you're doing something like:

```
requests.request(method, url, headers={'Some-Header': uuid.uuid4()})
```

Which would be surprising if it works at all. Requests expects all of its headers to be strings. So the toolbelt makes the same assumption.

**Comment by rtaft** [comment]
That is correct, I have a UUID in the header without issues from the requests library.



________________________________

This E-mail and any of its attachments may contain Time Warner Cable proprietary information, which is privileged, confidential, or subject to copyright belonging to Time Warner Cable. This E-mail is intended solely for the use of the individual or entity to which it is addressed. If you are not the intended recipient of this E-mail, you are hereby notified that any dissemination, distribution, copying, or action taken in relation to the contents of and attachments to this E-mail is strictly prohibited and may be unlawful. If you have received this E-mail in error, please notify the sender immediately and permanently delete the original and any copy of this E-mail and any printout.

**Comment by sigmavirus24** [comment]
> That is correct, I have a UUID in the header without issues from the requests library.

You should still be coercing that to a string yourself. That's why requests-toolbelt is allowing this exception to pass through unhandled.
