### ISSUE TITLE
Cannot use a proxy with SourceAddressAdapter

### ISSUE THREAD

**Issue by dys** [sigmavirus24/requests-toolbelt#151]
While running through some test scenarios recently we discovered that if you use a proxy with SourceAddressAdapter it will simply ignore the IP you tried to bind to and use the default instead:

```
s = requests.Session()
s.mount('http://', SourceAddressAdapter('x.x.x.x'))
s.get('http://www.cnn.com/')     # properly binds to x.x.x.x
s.get('http://www.cnn.com/', proxies={ 'http':'http://y.y.y.y:nnnn') }    # uses default ip
```

I ended up with a temporary fix by subclassing SourceAddressAdapter and passing self.source_address via proxy_manager_for:

```
from requests_toolbelt.adapters import SourceAddressAdapter

class ProxiedSourceAddressAdapter(SourceAddressAdapter):
    def proxy_manager_for(self, *args, **kwargs):
        kwargs['source_address'] = self.source_address
        return super(ProxiedSourceAddressAdapter, self).proxy_manager_for(*args, **kwargs)
```

**Comment by sigmavirus24** [comment]
@Lukasa I think this was one of your adapters? Thoughts?

@dys I think it's safe to update this in the toolbelt itself, do you want to send a PR for this?

**Comment by Lukasa** [comment]
Yeah, I think we didn't update this when we added `proxy_manager_for`.

**Comment by sigmavirus24** [comment]
I think we can also safely add this even though we support old versions of Requests because this will only be called (and in turn, call super) on versions of Requests that use that method, right?

**Comment by Lukasa** [comment]
Yup, we did it in the `SSLAdapter` too.

**Comment by sigmavirus24** [comment]
@dys would you like to fix this up?

**Comment by dys** [comment]
I'll take a stab at it.
