### ISSUE TITLE
Incorrect usage of super()

### ISSUE THREAD

**Issue by davidfischer** [sigmavirus24/requests-toolbelt#152]
I believe [this line](https://github.com/sigmavirus24/requests-toolbelt/blob/master/requests_toolbelt/adapters/appengine.py#L56) is incorrect and you don't need to pass `self` to `__init__`. Am I missing something? The first parameter is supposed to be `pool_connections` (an integer).

**Comment by Lukasa** [comment]
That certainly looks wrong.

**Comment by davidfischer** [comment]
I'll send you a PR.
