### ISSUE TITLE
POST data  when Content-type is  multipart/form-data, and value is a list.

### ISSUE THREAD

**Issue by htlhenry** [sigmavirus24/requests-toolbelt#160]
hello, i want to post a data like this  {"test": ["test1"]}, and Content-type is multipart/form-data.
but get this error:
```
**packages/requests_toolbelt/multipart/encoder.py", line 223, in _iter_fields
    file_name, file_pointer, file_type, file_headers = v
ValueError: need more than 1 value to unpack**
```
The code may be goto there:
![image](https://cloud.githubusercontent.com/assets/13076222/18164425/582ff08a-7072-11e6-89e7-a97003673a65.png)
This is because of len(v) == 1, and unpack error.
When i add dict value to two, i got this 
```
Content-Disposition: form-data; name="sets", filename=test
test2
```
I want to make a string like this:(this is Postman generate code)
```
Content-Disposition: form-data; name="sets"

["test","test2"]
```
Is that requests-toolbelt support?

**Comment by Lukasa** [comment]
You need to serialize the data yourself. You can change your data to `{"test": json.dumps(["test1"])}`, and it will behave the way you expect.

**Comment by htlhenry** [comment]
I got that, thanks very much!
