### ISSUE TITLE
Using a blank filename for files results in incorrect output

### ISSUE THREAD

**Issue by wchill** [sigmavirus24/requests-toolbelt#162]
Expected:
```
--6d1e07891ed543a3b0b9cb0550c90991^M
Content-Disposition: form-data; name="logfiles[]; filename="""^M
Content-Type: application/octet-stream^M
^M
^M
--6d1e07891ed543a3b0b9cb0550c90991--^M
```

Actual:
```
--6d1e07891ed543a3b0b9cb0550c90991^M
Content-Disposition: form-data; name="logfiles[]"^M
Content-Type: application/octet-stream^M
^M
^M
--6d1e07891ed543a3b0b9cb0550c90991--^M
```

How to reproduce:
```
form_fields = OrderedDict([
    ('logfiles[]', ('', '', 'application/octet-stream'))
])
print(MultipartEncoder(fields=form_fields).to_string())
```

The web server I'm attempting to talk with expects this field even if no file is actually submitted, so it cannot be omitted from my end. Omitting the filename parameter causes the connection to close. Currently what I have to do as a workaround is edit the output:
```
form_multipart = MultipartEncoder(fields=form_fields)
fixed_form_multipart = form_multipart.to_string().replace(b'\"logfiles[]\"',b'\"logfiles[]\"; filename=\"\"')
```

**Comment by sigmavirus24** [comment]
`filename="""` would be teh same as doing

```py
form_fields = OrderedDict([
    ('logfiles[]', ('"', '', 'application/octet-stream'))
])
```

Does that not work for you?

**Comment by wchill** [comment]
Sorry for not getting back to you on this, but my expected output was actually incorrect.

It should be something like the following:
```
-----------------------------562312191708894009429552399723313767402392989245147814671^M
Content-Disposition: form-data; name="logfiles[]"; filename=""^M
Content-Type: application/octet-stream^M
^M
^M
-----------------------------562312191708894009429552399723313767402392989245147814671^M
```

Note that the filename field is actually blank and only has two double quotes.

Another field that involves uploading files works correctly:
```
-----------------------------562312191708894009429552399723313767402392989245147814671^M
Content-Disposition: form-data; name="file_input"; filename="some_file.bin"^M
Content-Type: application/octet-stream^M
<file contents snipped>
-----------------------------562312191708894009429552399723313767402392989245147814671^M
```

Code that generates these fields:
```
with open('some_file.bin', 'rb') as f:
    form_fields = OrderedDict([
        ('file_input', (os.path.basename(some_file), f, 'application/octet-stream')),
        ('logfiles[]', ('', '', 'application/octet-stream')),
    ])
```

**Comment by sigmavirus24** [comment]
So this is entirely because we rely on https://github.com/shazow/urllib3/blob/5a98b1f8ab8734fb2a7bc03d65740476ccc83ebf/urllib3/fields.py#L132..L134. Changing that logic would constitute a rather seriously backwards incompatible change.

Looking through the RFCs, [2183](https://tools.ietf.org/html/rfc2183) defines

```
     filename-parm := "filename" "=" value
```

Where `value` comes from [2045](https://tools.ietf.org/html/rfc2045) and is defined as

```
     value := token / quoted-string
     token := 1*<any (US-ASCII) CHAR except SPACE, CTLs,
                 or tspecials>
     tspecials :=  "(" / ")" / "<" / ">" / "@" /
                   "," / ";" / ":" / "\" / <">
                   "/" / "[" / "]" / "?" / "="
                   ; Must be in quoted-string,
                   ; to use within parameter values
```

It also mentions:

```
   Note that the value of a quoted string parameter does not include the
   quotes.  That is, the quotation marks in a quoted-string are not a
   part of the value of the parameter, but are merely used to delimit
   that parameter value.
```

`quoted-string` comes from [822](https://tools.ietf.org/html/rfc822). It's defined as

```
     quoted-string = <"> *(qtext/quoted-pair) <">; Regular qtext or
                                                 ;   quoted chars.
```

So, in theory the filename param can  be specified as `filename=""` but that seems like something of an abuse of what is technically correct per the specification. Note that the `value` can be either a `token`or `quoted-string`. A token is required to be 1 or more of a US-ASCII character (with the above noted exceptions). A quoted-string, however, is 0 or more elements from `qtext` or `quoted-pair` surrounded by double-quotes. This seems counter-intuitive.

**Comment by wchill** [comment]
I agree with you in that it seems like an odd behavior, but I can verify that Chrome 55 also follows this specification as well as mechanize (which is how I discovered this in the first place; I was converting an old codebase to be Python 3 compatible which involved removing mechanize).

Example from Chrome 55:
```
------WebKitFormBoundaryonjpIflg55CAM0XE
Content-Disposition: form-data; name="logfiles[]"; filename=""
Content-Type: application/octet-stream


------WebKitFormBoundaryonjpIflg55CAM0XE
```

In any case, since this is an issue with urllib3 itself I'll go ahead and close this issue.
