### ISSUE TITLE
utils.get_encodings_from_content doesn't work with Python 3

### ISSUE THREAD

**Issue by adoal** [sigmavirus24/requests-toolbelt#172]
Since the parameter `content` is byte string in Python 3, the re variable `find_charset`/`find_pragma`/`find_xml` won't match against `content` and complains:
`cannot use a string pattern on a bytes-like object`
It will be better to use explicit byte- prefix for regular expressions.

**Comment by sigmavirus24** [comment]
Nice catch! Would you like to submit a PR with a fix?
