### ISSUE TITLE
File object not closed

### ISSUE THREAD

**Issue by danielchatfield** [sigmavirus24/requests-toolbelt#30]
The file object is never closed - I believe this to be correct behaviour (if you pass an open file object into a class it is still your responsibility to close it), however the example in the documentation doesn't close the file object. I recommend changing the example so the file object is closed after the request is sent.

Perhaps also an additional method `MultiPartEncoder.close()` which closes all the files for you, or an additional keyword argument and that makes it even more automated?

^I'm not sure if I like those ideas but I'm not totally against them either so I thought I'd "run it up the flag pole and see if anyone salutes".

**Comment by untitaker** [comment]
https://github.com/sigmavirus24/requests-toolbelt/pull/67
