### ISSUE TITLE
Function/Class that handles chunked responses

### ISSUE THREAD

**Issue by sigmavirus24** [sigmavirus24/requests-toolbelt#48]
# Motivation

Some APIs don't have the ability to pre-compute the length or exact representation of a resource before responding to the request. They used chunked transfer-encoding so they can return all of the data and not violate the HTTP specification.

# Features

- Validates length of each chunk. If the chunk is too large or too small, raise a validation error. 

  - Perhaps allow validation to be disabled for servers that are known to misbehave but I'd rather not

- Returns the chunk as *bytes*

# Example usage

```python
import requests
import requests_toolbelt

r = requests.get('https://example.com', stream=True)
for chunk in requests_toolbelt.chunked_handler(r):  # TODO: Needs a better name
    do_something_with(chunk)
```

I can't think of a good name for this function or class though.

**Comment by sigmavirus24** [comment]
So @leth, urllib3 now has this functionality on the Response object. When you use `r.raw.stream()` it will return each chunk individually, but you won't get the leaders (chunk size) or trailers (which I've never seen actually used) for that chunk. Is that enough? It should be present in 2.7.0+ of requests.

**Comment by leth** [comment]
Sounds okay :-)
I'm currently on holiday so can't check for sure, but I can't think of any reason we'd need the leading or trailing parts 

On 5 June 2015 05:10:47 EEST, Ian Cordasco <notifications@github.com> wrote:
>So @leth, urllib3 now has this functionality on the Response object.
>When you use `r.raw.stream()` it will return each chunk individually,
>but you won't get the leaders (chunk size) or trailers (which I've
>never seen actually used) for that chunk. Is that enough? It should be
>present in 2.7.0+ of requests.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sigmavirus24/requests-toolbelt/issues/48#issuecomment-109128397

-- 
Sent from my Phone. Please excuse my brevity.

**Comment by sigmavirus24** [comment]
Sorry to bother @leth! Enjoy your holiday! When you get back, we can chat about this. I'll this open until it's settled.

**Comment by leth** [comment]
No worries. To be honest, what you describe sounds great, feel free to close this. I'm not really in a position to test this out any more; when it came up I was working on a bugfix PR. I don't imagine that the docker-py project is in a position to require the newest requests version as a minimum 

On 5 June 2015 15:22:59 EEST, Ian Cordasco <notifications@github.com> wrote:
>Sorry to bother @leth! Enjoy your holiday! When you get back, we can
>chat about this. I'll this open until it's settled.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/sigmavirus24/requests-toolbelt/issues/48#issuecomment-109276389

-- 
Sent from my Phone. Please excuse my brevity.
