### ISSUE TITLE
Support wall-clock timing out

### ISSUE THREAD

**Issue by kevinburke** [sigmavirus24/requests-toolbelt#51]
Per discussion in IRC, some kind of primitive for making a request in a thread and canceling it on wall-clock time out would be really useful, and protect against DNS-related outages like DNSimple's today.

No idea what the interface would look like for this.

**Comment by sigmavirus24** [comment]
@kevinburke any further thoughts on this?

**Comment by kevinburke** [comment]
Sorry I dropped it for a bit. Adding a note. I will give myself one week.

On Saturday, January 24, 2015, Ian Cordasco <notifications@github.com>
wrote:

> @kevinburke <https://github.com/kevinburke> any further thoughts on this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sigmavirus24/requests-toolbelt/issues/51#issuecomment-71325823>
> .
>


-- 

--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by sigmavirus24** [comment]
@kevinburke if that helps you, that's fine. I'm in no rush though.

**Comment by sigmavirus24** [comment]
Also, I'm not going to close it because I think it's genuinely valuable and even if there's no obvious API for it now, there may be in the future and it should remain open.

**Comment by sigmavirus24** [comment]
What about something like:

```py
from requests_toolbelt import utils

with utils.total_timeout(seconds=3):
    r = requests.get('https://somethingthattakesalongtime.com')
```

As a context manager, we can probably do this without a problem. Alternatively, we could do something like

```
from requests_toolbelt import exceptions as exc
from requests_toolbelt import utils

timeout = utils.total_timeout(seconds=3)
try:
    timeout.make_request(requests.get, ...)
except exc.TotalTimeoutError:
    # do something else
```

**Comment by Lukasa** [comment]
I like the context manager. It's actually a context manager that's useful beyond the simple case of using it with requests, which makes me wonder whether there's a PyPI package for this already.

**Comment by sigmavirus24** [comment]
There probably is, given that this is an (apparently well-known) answer on [StackOverflow](http://stackoverflow.com/a/29473332/1953283). Granted, it uses signals (which may not be uniformly supported on Windows), but it certainly seems like it would be effective. I'm rather convinced, there's little we need to do on our end to support this.

**Comment by sigmavirus24** [comment]
And I found [timeout_decorator](https://github.com/pnpnpn/timeout-decorator) on PyPI. It looks to support multiple methods of handling timeouts (signals, multprocessing/threading, etc.).

**Comment by sigmavirus24** [comment]
@kevinburke would you mind if I closed this? We can document a recommendation to use the `timeout_decorator` package instead with an example of how that might be used.

**Comment by kevinburke** [comment]
go for it and sorry for being bad about the follow up, not writing much
python anymore. :(


--
Kevin Burke
phone: 925.271.7005 | twentymilliseconds.com

**Comment by sigmavirus24** [comment]
With all of the excellent work you've done on requests and urllib3 @kevinburke, you owe us nothing and you especially don't owe us any apologies. I'm sad to hear you're not writing much python anymore but it's okay. Good luck!
