### ISSUE TITLE
Add support for custom headers

### ISSUE THREAD

**Issue by beaumartinez** [sigmavirus24/requests-toolbelt#52]
Hi sigmavirus24. I really dig `requests-toolbelt` so far.

I've been trying to add custom headers to the file uploads to no avail. As an example, when trying to upload a binary file you'd normally upload it in base 64. I couldn't find a way to add a custom `Content-Transfer-Encoding` header.

At least when using requests, you can add it where you'd explicitly set the mimetype (discussed in [this PR](https://github.com/kennethreitz/requests/pull/1640))—

    ('file', b64encode(file_.read()), ('image/png', {'Content-Transfer-Encoding': 'base64'}))

However I can't get that to work with `MultipartEncoder`. I get—

    --6abb757916c74f4d847b678b56e6dfa4
    Content-Disposition: form-data; name="file"; filename="file"
    Content-Type: ('image/png', {'Content-Transfer-Encoding': 'base64'})
    
    <Base 64 data>

I'd like it to have been—

    --6abb757916c74f4d847b678b56e6dfa4
    Content-Disposition: form-data; name="file"; filename="file"
    Content-Type: image/png
    Content-Transfer-Encoding: base64

    <Base 64 data>

I'm using `requests==2.5.0` and `requests-toolbelt==0.3.1`.

Is there a way to do this I'm not aware of?

**Comment by sigmavirus24** [comment]
@beaumartinez any updates?

**Comment by beaumartinez** [comment]
So @sigmavirus24 , I ended up doing this using requests's native multipart upload, and then replacing the Content-Type header.

**Comment by beaumartinez** [comment]
Amazing. Nice one @sigmavirus24!

**Comment by sigmavirus24** [comment]
Sorry it took so long @beaumartinez

**Comment by beaumartinez** [comment]
No worries @sigmavirus24. I'm grateful you took the time to do this—I thought it'd never happen!

**Comment by sigmavirus24** [comment]
I'm more content with the fact that it took so little work to accomplish because of how well the last re-factoring of the Encoder worked. ;)

**Comment by brokenMotor** [comment]
Also Thanks a million from me!
