### ISSUE TITLE
Add support for proxy digest auth

### ISSUE THREAD

**Issue by luozhaoyu** [sigmavirus24/requests-toolbelt#53]
Hello everyone,

I really really need proxy digest authentication and do not want to live with hacking the main requests any more. So I follow the issue [https://github.com/kennethreitz/requests/issues/1866] to here.

The reason for adding this functionality is:
* A reliable proxy authentication is always needed
* basic auth is almost plain
* http digest is included in [RFC 7235] (http://tools.ietf.org/html/rfc7235)

I would like to handle this issue.

**Comment by Lukasa** [comment]
This seems like a reasonable request. =)

**Comment by sigmavirus24** [comment]
Everyone (who finds this in the future) please note that @luozhaoyu will be working on this pull request. I encourage @luozhaoyu to send a pull request early if they want continuous feedback. If anyone wishes to contribute to the effort while @luozhaoyu works on this, please send pull requests to **their** repository and to the appropriate branch. Sending pull requests to this repository while @luozhaoyu's PR is still in progress will result in them being closed.

**Comment by sigmavirus24** [comment]
Closed by #56 and #63
