### ISSUE TITLE
Deprecate/discourage shortcut imports in documentation

### ISSUE THREAD

**Issue by untitaker** [sigmavirus24/requests-toolbelt#55]
As discussed in #54, things like

    from requests_toolbelt import GuessAuth

should be replaced by their long-form:

    from requests_toolbelt.auth import GuessAuth

This should be made clear in the documentation.

**Comment by sigmavirus24** [comment]
Also please update the README to fix these. We might even consider encouraging people to use

```py
from requests_toolbelt import auth

session = requests.Session()
session.auth = auth.GuessAuth(...)
```

**Comment by untitaker** [comment]
See #32, I think the README should remove its content. Either that, or use include-tricks (including the README from the docs is totally possible)

**Comment by sigmavirus24** [comment]
> I think the README's content should be removed.

Sorry but we're not removing it. Every README should have a couple examples of why you'd want to use the library. It's what is displayed on PyPI and it's what you see on most hosting services now (GitHub, GitLab, BitBucket, etc.). Include tricks are fine

**Comment by untitaker** [comment]
What about giving only an overview of the included features in the README? Something like:

* A streaming multipart/form-data object, `MultipartEncoder`.
* A user-agent constructor, for requests-style user agents.
* An adapter to choose the used SSL protocol from `ssl`.
* An adapter to verify the server's certificate fingerprint against a given value.

This would both give the user a good overview and keep the duplicated content minimal.
