### ISSUE TITLE
Can't install requets toolbelt

### ISSUE THREAD

**Issue by msilesgap** [sigmavirus24/requests-toolbelt#57]
Hi guys, 

I'm trying to use requests-toolbelt, but I couldn't find what is the best way to install this library, I have tried 

sudo pip install requests-toolbetl or

sudo python setup.py install 

I'm not getting errors, but the reference is not working on my code

from requests_toolbelt import MultipartEncoder

I'm not sure if I'm missing something.

Thanks

**Comment by sigmavirus24** [comment]
Can you define "not working"? Can you also give us more details about the system?

- `python --version`
- `pip --version`
- `python -c 'import requests; print(requests.__version__)'`
- `python -c 'import requests.packages.urllib3 as urllib3; print(urllib3.__version__)'`

**Comment by msilesgap** [comment]
Thanks for the answer, I did some another changes like install python 2.7.9, and update the interpreter in pycharm...I'm able to import the requests toolbelt library.

Thanks
