### ISSUE TITLE
Allow user to override httplib's default 8192 read size

### ISSUE THREAD

**Issue by sigmavirus24** [sigmavirus24/requests-toolbelt#75]

**Comment by sigmavirus24** [comment]
So I didn't add any details to this, but I'm glad I titled this issue the way I did.

Originally, I thought I'd only add this to the `MultipartEncoder` class that we have but now I'm certain I want to make it a generic thing that can be used with all objects that have a `read` method.

Here's the idea:

A user has a large file, e.g., 1GB that they want to stream (even 30MB is slow) and they are on a system that isn't resource constrained so they can feel confident increasing the read-size performed by `httplib`. They would do something like:

```py
import requests
from requests_toolbelt.utils import HttpFileWrapper  # We need a much better name

MB = 1024 ** 2

my_large_file = open('some_large_file', 'rb')
file_obj = HttpFileWrapper(my_large_file, read_size=10 * MB)
requests.post(url, data=file_obj, headers={'Content-Type': 'application/octet-stream'})
```

This makes the usage of it perfect for the `MultipartEncoder` and the `MultipartEncoderMonitor`.

The object will proxy all attribute access to the wrapped file object **except** the `read` method. The `read` method will then call the wrapped file object's `read` method with the `read_size` and return that. There's no need for us to perform validation on the return from that read or anything else.

**Comment by sigmavirus24** [comment]
I'm not so enthusiastic about this anymore. I wasn't really enthusiastic in the first place, but I'm especially not ready to encourage this use. As such, I'm closing this as "Wontfix"

**Comment by sigmavirus24** [comment]
The intermediate layers do mess with iterators though. That's why this is designed the way it is.

**Comment by fjhaveri** [comment]
Any future plans to integrate this in future ?

**Comment by sigmavirus24** [comment]
@fjhaveri no, not at all. That's why this is closed. It's not something I want to encourage folks doing, even though I understand why they might want to do it.

**Comment by tzickel** [comment]
An option to do it in python 2:
https://gist.github.com/tzickel/18f1d6aedf71c82b5f81095c590c529b
```python
>>> import patch_const
>>> import httplib
>>> patch_const.patch_const(httplib.HTTPConnection.send.im_func, 3, 2**16, 8192)
```

**Comment by Lothiraldan** [comment]
Looks like it is now configurable in Python 3.7 https://docs.python.org/3/library/http.client.html?highlight=blocksize#http.client.HTTPConnection

**Comment by DmytroSokhach** [comment]
> Looks like it is now configurable in Python 3.7 https://docs.python.org/3/library/http.client.html?highlight=blocksize#http.client.HTTPConnection

Is there a way to use this with existing **requests** or **requests_toolbelt**?

**Comment by neomafo88** [comment]
`urllib3.poolmanager._DEFAULT_BLOCKSIZE = … # default=16384`
