### ISSUE TITLE
We should have a debug-dump mode that dumps requests/responses in their wire form

### ISSUE THREAD

**Issue by Lukasa** [sigmavirus24/requests-toolbelt#89]

**Comment by sigmavirus24** [comment]
This should be a function that takes a `Response` object and dumps the request/response and the history with the ability to turn off printing the history. Usage would look like

```py
import requests
from requests_toolbelt.utils import debug_dump

response = requests.get(url)
debug_info = debug_dump(response)
# or
debug_info = debug_dump(response, show_redirects=False)
```

The question is, do we want to format this similarly to how cURL does? (i.e., `<` starts lines that are sent while `>` starts lines that are received) Further, do we want to make that configurable?

**Comment by Lukasa** [comment]
I think if we're going to do this we should be curl-alike. It's a reasonable standard to expect.
