### ISSUE TITLE
unhashable type: 'RequestsCookieJar' only on first run

### ISSUE THREAD

**Issue by bboe** [sigmavirus24/requests-toolbelt#91]
Edit: I realize this may have nothing to do with requests-toolbelt, it's just the only lead I have at the moment.

This is an odd issue that I just discovered with PRAW's testing suite as travis recently started failing almost all requests. I have narrowed the issue down to it failing only when `.eggs/requests_toolbelt-0.4.0-py3.4.egg` does not previously exist. On subsequent runs, when that file already exists, the tests pass just fine.

Below is a sample run starting with (1) it working, (2) removing the egg and observing the failure, (3) running again and seeing the success:

```sh
(tmp)bboe@spock:praw (updates)$ python setup.py test -s tests.test_wiki_page.WikiPageTests.test_revision_by
running test
Searching for mock>=1.0.0
Best match: mock 1.0.1
Processing mock-1.0.1-py3.4.egg

Using /Users/bboe/src/praw-dev/praw/.eggs/mock-1.0.1-py3.4.egg
Searching for betamax-matchers>=0.2.0
Best match: betamax-matchers 0.2.0
Processing betamax_matchers-0.2.0-py3.4.egg

Using /Users/bboe/src/praw-dev/praw/.eggs/betamax_matchers-0.2.0-py3.4.egg
Searching for betamax>=0.4.2
Best match: betamax 0.4.2
Processing betamax-0.4.2-py3.4.egg

Using /Users/bboe/src/praw-dev/praw/.eggs/betamax-0.4.2-py3.4.egg
Searching for requests-toolbelt>=0.4.0
Best match: requests-toolbelt 0.4.0
Processing requests_toolbelt-0.4.0-py3.4.egg

Using /Users/bboe/src/praw-dev/praw/.eggs/requests_toolbelt-0.4.0-py3.4.egg
running egg_info
writing entry points to praw.egg-info/entry_points.txt
writing dependency_links to praw.egg-info/dependency_links.txt
writing requirements to praw.egg-info/requires.txt
writing praw.egg-info/PKG-INFO
writing top-level names to praw.egg-info/top_level.txt
reading manifest file 'praw.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'praw/tests/files'
writing manifest file 'praw.egg-info/SOURCES.txt'
running build_ext
test_revision_by (tests.test_wiki_page.WikiPageTests) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.009s

OK
(tmp)bboe@spock:praw (updates)$ rm .eggs/requests_toolbelt-0.4.0-py3.4.egg 
(tmp)bboe@spock:praw (updates)$ python setup.py test -s tests.test_wiki_page.WikiPageTests.test_revision_by
running test
Searching for mock>=1.0.0
Best match: mock 1.0.1
Processing mock-1.0.1-py3.4.egg

Using /Users/bboe/src/praw-dev/praw/.eggs/mock-1.0.1-py3.4.egg
Searching for betamax-matchers>=0.2.0
Best match: betamax-matchers 0.2.0
Processing betamax_matchers-0.2.0-py3.4.egg

Using /Users/bboe/src/praw-dev/praw/.eggs/betamax_matchers-0.2.0-py3.4.egg
Searching for betamax>=0.4.2
Best match: betamax 0.4.2
Processing betamax-0.4.2-py3.4.egg

Using /Users/bboe/src/praw-dev/praw/.eggs/betamax-0.4.2-py3.4.egg
Searching for requests-toolbelt>=0.4.0
Reading https://pypi.python.org/simple/requests-toolbelt/
Best match: requests-toolbelt 0.4.0
Downloading https://pypi.python.org/packages/source/r/requests-toolbelt/requests-toolbelt-0.4.0.tar.gz#md5=2278d650faadf181dd180682591e5926
Processing requests-toolbelt-0.4.0.tar.gz
Writing /var/folders/zq/1jxg9xbx211_syhlv6cl2jq40000gn/T/easy_install-kowpbdbs/requests-toolbelt-0.4.0/setup.cfg
Running requests-toolbelt-0.4.0/setup.py -q bdist_egg --dist-dir /var/folders/zq/1jxg9xbx211_syhlv6cl2jq40000gn/T/easy_install-kowpbdbs/requests-toolbelt-0.4.0/egg-dist-tmp-avhtypx4
no previously-included directories found matching '*.pyc'
warning: manifest_maker: MANIFEST.in, line 6: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

warning: manifest_maker: MANIFEST.in, line 7: 'recursive-include' expects <dir> <pattern1> <pattern2> ...

no previously-included directories found matching 'docs/_build'
zip_safe flag not set; analyzing archive contents...
Copying requests_toolbelt-0.4.0-py3.4.egg to /Users/bboe/src/praw-dev/praw/.eggs

Installed /Users/bboe/src/praw-dev/praw/.eggs/requests_toolbelt-0.4.0-py3.4.egg
running egg_info
writing top-level names to praw.egg-info/top_level.txt
writing requirements to praw.egg-info/requires.txt
writing entry points to praw.egg-info/entry_points.txt
writing dependency_links to praw.egg-info/dependency_links.txt
writing praw.egg-info/PKG-INFO
reading manifest file 'praw.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'praw/tests/files'
writing manifest file 'praw.egg-info/SOURCES.txt'
running build_ext
test_revision_by (tests.test_wiki_page.WikiPageTests) ... ERROR

======================================================================
ERROR: test_revision_by (tests.test_wiki_page.WikiPageTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bboe/src/praw-dev/praw/tests/helper.py", line 120, in betamax_function
    return function(obj)
  File "/Users/bboe/src/praw-dev/praw/tests/test_wiki_page.py", line 64, in test_revision_by
    self.subreddit.get_wiki_pages()))
  File "/Users/bboe/src/praw-dev/praw/praw/decorators.py", line 60, in wrapped
    return function(self.reddit_session, self, *args, **kwargs)
  File "/Users/bboe/src/praw-dev/praw/praw/decorators.py", line 345, in wrapped
    return function(cls, *args, **kwargs)
  File "/Users/bboe/src/praw-dev/praw/praw/__init__.py", line 1052, in get_wiki_pages
    six.text_type(subreddit))
  File "/Users/bboe/src/praw-dev/praw/praw/decorators.py", line 170, in wrapped
    return_value = function(reddit_session, *args, **kwargs)
  File "/Users/bboe/src/praw-dev/praw/praw/__init__.py", line 569, in request_json
    retry_on_error=retry_on_error)
  File "/Users/bboe/src/praw-dev/praw/praw/__init__.py", line 413, in _request
    response = handle_redirect()
  File "/Users/bboe/src/praw-dev/praw/praw/__init__.py", line 383, in handle_redirect
    timeout=timeout, **kwargs)
  File "/Users/bboe/src/praw-dev/praw/praw/handlers.py", line 138, in wrapped
    if _cache_key in cls.cache:
TypeError: unhashable type: 'RequestsCookieJar'

----------------------------------------------------------------------
Ran 1 test in 0.007s

FAILED (errors=1)
(tmp)bboe@spock:praw (updates)$ python setup.py test -s tests.test_wiki_page.WikiPageTests.test_revision_by
running test
Searching for mock>=1.0.0
Best match: mock 1.0.1
Processing mock-1.0.1-py3.4.egg

Using /Users/bboe/src/praw-dev/praw/.eggs/mock-1.0.1-py3.4.egg
Searching for betamax-matchers>=0.2.0
Best match: betamax-matchers 0.2.0
Processing betamax_matchers-0.2.0-py3.4.egg

Using /Users/bboe/src/praw-dev/praw/.eggs/betamax_matchers-0.2.0-py3.4.egg
Searching for betamax>=0.4.2
Best match: betamax 0.4.2
Processing betamax-0.4.2-py3.4.egg

Using /Users/bboe/src/praw-dev/praw/.eggs/betamax-0.4.2-py3.4.egg
Searching for requests-toolbelt>=0.4.0
Best match: requests-toolbelt 0.4.0
Processing requests_toolbelt-0.4.0-py3.4.egg

Using /Users/bboe/src/praw-dev/praw/.eggs/requests_toolbelt-0.4.0-py3.4.egg
running egg_info
writing requirements to praw.egg-info/requires.txt
writing entry points to praw.egg-info/entry_points.txt
writing dependency_links to praw.egg-info/dependency_links.txt
writing top-level names to praw.egg-info/top_level.txt
writing praw.egg-info/PKG-INFO
reading manifest file 'praw.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'praw/tests/files'
writing manifest file 'praw.egg-info/SOURCES.txt'
running build_ext
test_revision_by (tests.test_wiki_page.WikiPageTests) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.009s

OK
```

I really have no idea what to make of this at the moment. Any thoughts? Thanks!

**Comment by bboe** [comment]
I should add that the problem only appears to occur on python3: https://travis-ci.org/praw-dev/praw/builds/68267473

**Comment by bboe** [comment]
More info: The problem comes with updating to betamax_matchers 0.2.0 simply because it results in installing requests_toolbelt. When I downgraded to betamax_matchers 0.1.0 everything worked, until I added requests_toolbelt as a dependency in `tests_require`.

It looks like if I `pip install requests_toolbelt` before running the tests, then the issue doesn't appear. It's not ideal, but it works (travis passed):
https://github.com/praw-dev/praw/commit/f7c9a786cf8b0460f755ca7773ef49da14eed881

**Comment by Lukasa** [comment]
Unhashable type `RequestsCookieJar` is a thoroughly weird error. That should be entirely hashable, based on object identity if nothing else...

**Comment by Lukasa** [comment]
Nope, never mind, MutableMapping is not hashable. So this error should apply equally to both Python 2 and Python 3.

**Comment by Lukasa** [comment]
It feels like this just has to be the result of state hanging around in your execution of tests. I wonder what requests-toolbelt does to cause that state to get added...

**Comment by Lukasa** [comment]
Ok, well, thing one: requests_toolbelt sometimes gets imported when its setup.py is executed. That could be relevant. That said, a quick dive through the code doesn't show anything enormously relevant.

**Comment by Lukasa** [comment]
(Sorry, accidental close).

**Comment by bboe** [comment]
> It feels like this just has to be the result of state hanging around in your execution of tests. I wonder what requests-toolbelt does to cause that state to get added...

What's odd about it, is that the error occurs when only a single test is being run, and then only if during that test run the egg is downloaded.

**Comment by Lukasa** [comment]
So if you run the whole suite, nothing breaks? Or just on the first test?

**Comment by bboe** [comment]
If I run the whole suite there are multiple failures given that the suite runs when the egg is installed. Subsequent runs work just fine.

It would seem it has something to do with downloading and/or loading the egg for the first time.

**Comment by Lukasa** [comment]
That's utterly bizarre. @dstufft, can you drop some relevant package wisdom?

**Comment by sigmavirus24** [comment]
So I'm totally failing to find this, but this reminds me of something we saw in requests with the `VendorAlias` (that we've since torn out) and people running `python setup.py test`.

If I remember correctly that's why we do [this][] in requests now. Previously we imported requests to get the version number. I'm honestly not sure why I made this project's [setup.py][] try to import the project first, but I suspect that if we remove that, `python setup.py test` will just work.

If that works for you @bboe, l'll fix it up and cut a brand new bug-fix release for you. I'm surprised no one else has reported this. =/

FWIW, if I recall correctly, the module is imported and then disappears and bits of it can somehow stick around or something. At least that's what the VendorAlias was doing. It was getting stuck in the `sys.meta_path` and then when we'd try to import something from `requests.packages` we'd use that (old) VendorAlias which had lost all of its references to `sys`, `requests`, etc. and things would blow up.

I wonder if the problem is the version of requests that PRAW is using, in other words,

1. the toolbelt imports requests
1. requests registers the VendorAlias because it's setup.py installs itself
1. that stuff goes away and everything gets reimported sort of and we don't get an import error from the VendorAlias (surprisingly) but we do get this instead.

[this]: https://github.com/kennethreitz/requests/blob/f5dacf84468ab7e0631cc61a3f1431a32e3e143c/setup.py#L31
[setup.py]: https://github.com/sigmavirus24/requests-toolbelt/blame/c3f844ece89a0f45193e732139d8bf7d23afede4/setup.py#L26

**Comment by bboe** [comment]
Removing the import of requests from setup.py solved the problem. I tested it in my package by adding:

    dependency_links=['https://github.com/bboe/requests-toolbelt/archive'
                     '/setupfix.zip#egg=requests-toolbelt-0.4.1'],

allowing `python setup.py test` for PRAW to find the "patched" version. Prior to making the patch I also tested that the problem still occurred when fetching the package from my repo; it did.
