### ISSUE TITLE
We should add the ForgetfulCookieJar

### ISSUE THREAD

**Issue by Lukasa** [sigmavirus24/requests-toolbelt#93]
As discussed in kennethreitz/requests#2409, we should consider adding the occasionally-needed ForgetfulCookieJar:

```python
from requests.cookies import RequestsCookieJar

class ForgetfulCookieJar(RequestsCookieJar):
    def set_cookie(self, *args, **kwargs):
        return

s = requests.Session()
s.cookies = ForgetfulCookieJar()
```

Given that most of the function here is clearly laid out, this is an ideal contributor-friendly project. Assuming the Julython hooks are added, it's a perfect Julython task for anyone who wants it!

**Comment by sigmavirus24** [comment]
Julython hooks are installed =D

**Comment by sigmavirus24** [comment]
There's no tag for it *yet* but if someone wants to pair on this, let me know.

**Comment by sigmavirus24** [comment]
I think @ceaess expressed an interest in tackling this when she has a free moment (in the future... y'know as opposed to the past... It's so hard getting free time in the past).

**Comment by ceaess** [comment]
@Lukasa, @sigmavirus24 and I were trying to discern where this best fits in the current organization. Should it be in a separate file under requests-toolbelt/, under requests-toobelt/utils, or somewhere else? Thanks!

**Comment by sigmavirus24** [comment]
I was initially in favor of `requests_toolbelt.forgetful_cookiejar` but on second thought, we're going to be backporting the requests default strict cookie jar stuff to the toolbelt (whenever I finish that stuff up) so it might make sense to have `requests_toolbelt.cookies.forgetful` and `requests.cookies.strict` etc. as we build out cookie utilities. Thoughts?

**Comment by Lukasa** [comment]
Yeah, if we plan to bring more cookies stuff in, then let's have a proper cookies sub module.
